### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by moderGamer**
add Note

### CODE REVIEW

**Comment by DevKumar00001** [comment]
This is released bro

**Comment by moderGamer** [comment]
> 

@DevKumar00001  Accept this request so that some mentally retarded people cannot publish your program under their own name

**Comment by DevKumar00001** [comment]
And Readme should not contains this types of notices.

**Comment by DevKumar00001** [comment]
> > 
> 
> @DevKumar00001 Accept this request so that some mentally retarded people cannot publish your program under their own name

You know whatsapp.
In many stores it is available that doesn't means those versions are released by their developer

**Comment by moderGamer** [comment]
> 

@DevKumar00001 What did I tell you in Telegram?  Do the same thing

**Pull request closed without merging**
