### PR TITLE
Add CloneRepository github

### PR DESCRIPTION
**Pull request by PHANTOMLOCAL**

### CODE REVIEW

**Comment by DevKumar00001** [comment]
You forgot to implement library the main thing bro.

**Comment by PHANTOMLOCAL** [comment]
> You forgot to implement library the main thing bro.

Yes

**Comment by PHANTOMLOCAL** [comment]
I was forgetting

**Comment by PHANTOMLOCAL** [comment]
😂😂😂

**Comment by DevKumar00001** [comment]
Bro is there any way to auto approve and run?

**Comment by DevKumar00001** [comment]
Bro I am sure java JGit will not work on lower android version.
I saying leave it.
Bro you can see how badly I am writing code.
I meant I used double code many time.
And there are some methods that are only used one time.
For these can you make it properly?

For methods that are only used 1 time.Remove that method and add code instead of method.

For code that are used more that 1 time create a method for that code.

**Comment by DevKumar00001** [comment]
If you were using Kotlin it would work but I don't know kotlin.

**Comment by DevKumar00001** [comment]
If you know how to fix error that I sent you earlier then you can continue.

**Comment by PHANTOMLOCAL** [comment]
> اگر از کاتلین استفاده می کردید کار می کرد اما من کاتلین را نمی دانم.

**Comment by PHANTOMLOCAL** [comment]
> اگر از کاتلین استفاده می کنم می کنم اما من کاتلین را نمی دانم.

Why? Why not Java but Kotlin? Unfortunately, I don't know Kathleen very well Maybe this problem will be solved in the future, brother Should I continue to fix the errors?

**Comment by DevKumar00001** [comment]
Use english only.
And send translation also

**Comment by PHANTOMLOCAL** [comment]
> شما هنوز blankj را اضافه نکرده اید.

can you help

**Comment by DevKumar00001** [comment]
From now I am not going to run work flow as there are many failure in repository.
Enable work flow in your fork for test and once you are done open this pull request again.

**Comment by DevKumar00001** [comment]
> > شما هنوز blankj را اضافه نکرده اید.
> 
> can you help

First give me access to your whole fork.

**Comment by DevKumar00001** [comment]
> 

Use english.

**Comment by DevKumar00001** [comment]
Come online at telegram

**Comment by PHANTOMLOCAL** [comment]
این درخواست کشش بسته شد

**Pull request closed without merging**
