### PR TITLE
Add multi tabs

### PR DESCRIPTION
**Pull request by PHANTOMLOCAL**

### CODE REVIEW

**Comment by PHANTOMLOCAL** [comment]
Hi
Is the sheet layout better or recycled view? But I have used tab recycler view for multiple tabs in the past

**Comment by TechnicalStudioDeveloper** [comment]
> Hi Is the sheet layout better or recycled view? But I have used tab recycler view for multiple tabs in the past

I don't have any idea on that.
Choose according to you that works fine.

**Comment by TechnicalStudioDeveloper** [comment]
@PHANTOMLOCAL I fixed all error that I can but you sometimes used following methods.
`codeEditor.release();`
`codeEditor.getDocument()`
Please Note that don't implement these method on CodeEditorLayout

**Comment by TechnicalStudioDeveloper** [comment]
@PHANTOMLOCAL checkout these [errors too](https://github.com/TS-Code-Editor/Android-Code-Editor/actions/runs/5501353652/jobs/10028159363#step:5:81)

**Comment by TechnicalStudioDeveloper** [comment]
I tried to rerun but 26 errors are still [there](https://github.com/TS-Code-Editor/Android-Code-Editor/actions/runs/5501353652/jobs/10053242531)

**Comment by TechnicalStudioDeveloper** [comment]
I Added file tab system rather than tab layout but contains many bug that needs to be fix.
@PHANTOMLOCAL, @CyberGlitch01  please help to fix those bugs.
I am closing this pull request now.

**Pull request closed without merging**
